services:
  minio:
    image: minio/minio
    container_name: minio_nhvthan
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks:
      - minio_network
    command: server /data --console-address ":9001"

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local