services:
  weaviate:
    container_name: "weaviate_nhvthan"
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8081'
    - --scheme
    - http
    image: semitechnologies/weaviate
    ports:
    - "8081:8080"
    - "50051:50051"
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 50
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'backup-s3,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      BACKUP_S3_BUCKET: 'weaviate-backups'
      BACKUP_S3_ENDPOINT: ${MINIO_ENDPOINT}
      BACKUP_S3_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      BACKUP_S3_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      BACKUP_S3_USE_SSL: ${USE_SSL}
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - weaviate_network
volumes:
  weaviate_data:
    driver: local

networks:
  weaviate_network:
    driver: bridge